spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookportal?autoReconnect=true&useSSL=false
    username: root
    password: ozgur123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080